trigger:
  branches:
    include:
      - experimental/*
    exclude:
      - main
      - sandbox/*
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - script: echo "dotnet restore ContosoApp.sln"
    displayName: 'Restore packages'

  - script: echo "dotnet build ContosoApp.sln --configuration $(buildConfiguration) --no-restore"
    displayName: 'Build'

  - script: echo "dotnet test ContosoApp.sln --configuration $(buildConfiguration) --no-build"
    displayName: 'Test'    