trigger:
  branches:
    include:
      - main
      - experimental/testing

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '8.x'

          - script: echo "dotnet publish src/ContosoApp.Api/ContosoApp.Api.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)"
            displayName: 'Publish'  