trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildpipeline
      source: 'build-pipeline'
      trigger: true


pool: 
  vmImage: 'ubuntu-latest'

stages:
  - stage: Deploy
    displayName: 'Deploy to Staging'
    jobs:
      - deployment: DeployStaging
        environment: 'staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying artifacts from build $(resources.pipeline.buildpipeline.runID)"
                  displayName: 'Deploy API'    