trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: validate
    condition: startsWith(variables['System.PullRequest.SourceBranch'], 'experimental/')
    jobs:
      - job: BuildAndTest
        steps:

          - script: echo "dotnet restore ContosoApp.sln"
            displayName: 'Restore'
   